[package]
name = "mpDris"
description = "A client implementing the dbus MPRIS standard for mpd"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
const_format = "0.2.32"
dbus = "0.9.7"
serde = { version = "1.0.193", features = ["derive"] }
toml = "0.8.13"


[profile.release]
strip = true
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"
