name: Build, test and lint

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: -Dwarnings
  RUST_BACKTRACE: full

jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          components: rustfmt
      - uses: Swatinem/rust-cache@v2
      - name: Check formatting
        run: |
          cargo --locked fmt --check
          cargo --locked check

  clippy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          components: clippy
      - uses: Swatinem/rust-cache@v2
      - name: Catch clippy mistakes
        run: |
          cargo --locked clippy

  build:
    runs-on: ubuntu-latest
    needs: [fmt, clippy]
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup rust
      uses: dtolnay/rust-toolchain@stable
      with:
          toolchain: stable
    - uses: Swatinem/rust-cache@v2
    - name: Run tests
      run: cargo --locked test --verbose
    - name: Build package
      run: cargo --locked build --verbose
